GET http://localhost:9000/api/addres/631ffa435b418c5ba6a8e607

###
GET http://localhost:9000/api
###
GET http://localhost:9000/api/groupsPrices
###
GET http://localhost:9000/api/privacyPolicy
###
GET http://localhost:9000/api/public/assets/logos/noBGLogo.png"
###
GET http://localhost:9000/api/addresses
###
GET http://localhost:9000/api/address/64184f10de053c52c2509f27
###
GET http://localhost:9000/api/schedules?userId= 4
###
GET http://localhost:9000/api/users
###
GET https://sary.onrender.com/api
###
GET http://localhost:9000/api/driversConfirm/confirmed
